/**
 * backend/src/extractors/youtube.ts
 * ────────────────────────────────────
 * YouTube extractor via yt-dlp.
 * Supports: youtube.com/watch, youtu.be (+ ?si= tracking params), youtube.com/shorts
 *
 * ─── ROOT CAUSE OF "Requested format is not available" ON RAILWAY ───
 *
 * YouTube (2024–2026) applies multi-layer bot detection to datacenter IPs:
 *
 * LAYER 1 — po_token (Proof of Origin Token)
 *   Most player clients now require a po_token generated by the browser's
 *   JavaScript challenge. Datacenter IPs cannot solve this challenge.
 *   Affected clients: web_creator, default, web, android, ios (in some regions).
 *   Solution: use EMBED clients (tv_embedded, web_embedded) which YouTube
 *   explicitly permits for server-side use and do NOT require po_token.
 *
 * LAYER 2 — JS player fingerprinting
 *   yt-dlp normally downloads and executes the YouTube JS player to extract
 *   the stream signature cipher. This download itself can trigger bot detection.
 *   Solution: --extractor-args 'youtube:player_skip=webpage,configs,js'
 *   tells yt-dlp to use the cached/known cipher and skip the JS download.
 *
 * LAYER 3 — CDN format probing
 *   After getting format list, yt-dlp probes each CDN URL to verify
 *   availability. These probes are blocked from datacenter IPs.
 *   Solution: --no-check-formats + --skip-download in fetchInfo() (base.ts).
 *
 * ─── OPTIMAL CLIENT CHAIN FOR RAILWAY (2026) ────────────────────────
 *
 *   tv_embedded   → YouTube TV embed client. Server-side permitted. No po_token
 *                   required. Most reliable from Railway/GCP IPs. PRIMARY.
 *
 *   web_embedded  → YouTube iframe embed. Different endpoint from tv_embedded.
 *                   Also server-side permitted. SECONDARY fallback.
 *
 *   ios           → iOS app client. Uses AppAttest auth, different from web.
 *                   Not subject to browser po_token requirement. TERTIARY.
 *
 *   web_creator   → YouTube Studio client. Was primary in 2024, now requires
 *                   po_token from datacenter IPs in some regions. QUATERNARY.
 *
 *   mweb          → Mobile web client. Most permissive, lowest quality.
 *                   Fallback of last resort. FINAL.
 *
 * ─── ?si= TRACKING PARAMETER ────────────────────────────────────────
 *
 * YouTube mobile app appends ?si=<tracking_id> to shared URLs.
 * e.g. https://youtu.be/MLU5ZEp9YDo?si=9G3sKXw9lNEw5CNo
 *
 * Some yt-dlp versions pass this to YouTube's API which returns a
 * different (more restricted) response for tracked share links.
 * Solution: strip ALL query params except v= when normalising URLs.
 * Every YouTube video ID is always 11 characters — extract and rebuild clean URL.
 */

import { BaseExtractor } from './base.js';
import type { MediaMeta, PreviewMeta } from './index.js';

/**
 * Normalise any YouTube URL to a clean canonical watch URL.
 *
 * Handles:
 *   https://youtu.be/VIDEO_ID                         → watch?v=VIDEO_ID
 *   https://youtu.be/VIDEO_ID?si=TRACKING             → watch?v=VIDEO_ID  ← strips ?si=
 *   https://www.youtube.com/shorts/VIDEO_ID           → watch?v=VIDEO_ID
 *   https://www.youtube.com/watch?v=VIDEO_ID&t=30s    → watch?v=VIDEO_ID  ← strips &t=
 *   https://www.youtube.com/watch?v=VIDEO_ID&si=...   → watch?v=VIDEO_ID  ← strips ?si=
 *   https://www.youtube.com/embed/VIDEO_ID            → watch?v=VIDEO_ID
 *   https://www.youtube.com/live/VIDEO_ID             → watch?v=VIDEO_ID
 */
function normaliseYouTubeUrl(url: string): string {
  const cleaned = url.trim();
  let videoId: string | null = null;

  // youtu.be/VIDEO_ID (with any query string)
  const shortMatch = cleaned.match(/(?:https?:\/\/)?youtu\.be\/([A-Za-z0-9_-]{11})/);
  if (shortMatch) videoId = shortMatch[1]!;

  // youtube.com/shorts/VIDEO_ID
  if (!videoId) {
    const shortsMatch = cleaned.match(
      /(?:https?:\/\/)?(?:www\.)?youtube\.com\/shorts\/([A-Za-z0-9_-]{11})/
    );
    if (shortsMatch) videoId = shortsMatch[1]!;
  }

  // youtube.com/watch?v=VIDEO_ID (strips ALL other params including ?si= and &t=)
  if (!videoId) {
    const watchMatch = cleaned.match(
      /(?:https?:\/\/)?(?:www\.)?youtube\.com\/watch\?.*?[?&]?v=([A-Za-z0-9_-]{11})/
    );
    if (watchMatch) videoId = watchMatch[1]!;
  }

  // youtube.com/embed/VIDEO_ID
  if (!videoId) {
    const embedMatch = cleaned.match(
      /(?:https?:\/\/)?(?:www\.)?youtube\.com\/embed\/([A-Za-z0-9_-]{11})/
    );
    if (embedMatch) videoId = embedMatch[1]!;
  }

  // youtube.com/live/VIDEO_ID (live streams)
  if (!videoId) {
    const liveMatch = cleaned.match(
      /(?:https?:\/\/)?(?:www\.)?youtube\.com\/live\/([A-Za-z0-9_-]{11})/
    );
    if (liveMatch) videoId = liveMatch[1]!;
  }

  // Rebuild clean canonical URL — strips ALL tracking params (?si=, &t=, etc.)
  if (videoId) {
    return `https://www.youtube.com/watch?v=${videoId}`;
  }

  // Not a recognisable YouTube URL — return unchanged (yt-dlp handles it)
  return url;
}

export class YoutubeExtractor extends BaseExtractor {
  readonly platform = 'youtube';

  /**
   * Extra args for every yt-dlp call on YouTube.
   *
   * IMPORTANT — do NOT add here:
   *   --no-playlist  → base.ts adds it per-call (avoid duplicates)
   *   --no-warnings  → base.ts adds it per-call (avoid duplicates)
   *
   * Cookies come FIRST so the 'web' client in the chain has auth immediately.
   */
  protected extraArgs(): string[] {
    const args: string[] = [
      '--geo-bypass',
      '--force-ipv4',
    ];

    // Cookies decoded from YT_COOKIES_BASE64 by docker-entrypoint.sh at startup
    if (process.env.YT_COOKIES_FILE) {
      args.push('--cookies', process.env.YT_COOKIES_FILE);
    }

    // FIXED CLIENT ORDER for 2026 Railway/datacenter IPs:
    // Lead with EMBED clients (no po_token required by YouTube for server-side)
    // then fall back to ios (AppAttest auth, not browser-po_token restricted)
    // then web_creator as last real attempt before mweb fallback.
    // Two extractor-args combined with semicolon (correct yt-dlp format):
    //   player_client — ordered for Railway/datacenter IPs (embed clients first)
    //   player_skip   — skips JS player download to avoid bot fingerprinting
    // Format: 'youtube:KEY=VAL;KEY2=VAL2' (extractor name only on first key)
    args.push(
      '--extractor-args',
      'youtube:player_client=tv_embedded,web_embedded,ios,web_creator,mweb;player_skip=webpage,configs,js',
    );

    return args;
  }

  override async getMetadata(url: string): Promise<MediaMeta> {
    return super.getMetadata(normaliseYouTubeUrl(url));
  }

  override async getPreview(url: string): Promise<PreviewMeta> {
    return super.getPreview(normaliseYouTubeUrl(url));
  }

  override async getStreamUrl(url: string, formatId: string): Promise<string> {
    return super.getStreamUrl(normaliseYouTubeUrl(url), formatId);
  }
}
